GET http://localhost:3000/user

###
GET http://localhost:3000/user/1

###
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "John Doe",
  "profileId": 1
}

###
GET http://localhost:3000/user


###
POST http://localhost:3000/course
Content-Type: application/json

{
  "title": "Math 101"
}
